
Building blocks
===============
author: Bela Ban belaban@yahoo.com

Abstractions (to be used over a channel) such as clustered method
invocations, replicated hashmaps, distributed counters and locks.



Method invocations across a cluster
-----------------------------------
* Class `RpcDispatcher` (name derived from **R**emote **P**rocedure **C**alls) provides the capability of invoking
methods in a single node (unicast invocation), or in all nodes of a cluster (multicast invocation)
* Invocations can be _synchronous_ (blocking) or _non-synchronous_ (non-blocking)
* Any Java method can be invoked
* With multicast invocations, a `RspList<T>` object is returned:
[source,java]
----
public class RspList<T> implements Map<Address,Rsp<T>> {... }
----

* `RspList` is a map of `Rsp<T>` objects associated with their senders; there's 1 entry for each cluster node:
[source,java]
----
for(Rsp<Integer> rsp: rsps) {
    if(rsp.hasException()) {
        log.warn("exception for %s: %s", rsp.getSender(), rsp.getException());
        continue;
    }
    if(rsp.wasSuspected()) {
        System.out.printf("%s was suspected:\n", rsp.getSender());
        continue;
    }
    if(!rsp.wasReceived()) {
        System.out.printf("no rsp from %s (timeout)\n", rsp.getSender());
        continue;
    }
    System.out.printf("result for %s: %d\n", rsp.getSender(), rsp.getValue());
}
----


Rsp<T>
------
* A response is of type `Rsp<T>`:
[source,java]
----
public class Rsp<T> {
    public T         getValue() {...}
    public boolean   hasException() {...}
    public Throwable getException() {...}
    public Address   getSender() {...}
    public boolean   wasReceived() {...}
    public boolean   wasSuspected() {...}
}
----

* Method `getValue()` returns the value, or `null` if no value was received (or the method returned `void`)
* If `hasException()` is true, `getException()` will return a non-null `Throwable`
* Method `getSender()` returns the sender of this specific response
* Method `wasReceived()` returns true if the call completed successfully (even if it is a `void` method)
* Method `wasSuspected()` returns true if the member was suspected while waiting for its response



RequestOptions
--------------
* Every method invocation can be parameterized with an instance of `RequestOptions`. We can define
** Response mode: this determines whether the call is blocking and - if yes - how long it should block. The modes are:
  `GET_ALL`:: Block until responses from all members (minus the suspected ones) have been received.
  `GET_NONE`:: Wait for none. This makes the call non-blocking
  `GET_FIRST`:: Block until the first response (from anyone) has been received
  `GET_MAJORITY`:: Block until a majority of members have responded
** Timeout: max time (ms) to block. If the call hasn't completed after the timeout elapsed, a TimeoutException will be thrown.
   A timeout of 0 means to wait forever. Ignored if the call is non-blocking (mode=`GET_NONE`)
** Response filter: an `RspFilter` allows for filtering of responses and user-defined termination of
  a call. For example, if we expect responses from 10 members, but can return after having
  received 3 non-null responses, a `RspFilter` could be used. 
** Flags: the various flags to be passed to the message (re advanced section)
** Exclusion list: here we can pass a list of members (addresses) that should be excluded. For example,
  if the view is `{A,B,C,D,E}`, and we set the exclusion list to A,C then the caller will wait for
  responses from everyone except A and C. Also, every recipient that's in the exclusion list
  will discard the message.




RpcDispatcher API
-----------------

[source,java]
----
public <T> RspList<T>
       callRemoteMethods(Collection<Address> dests,
                         String method_name, Object[] args, Class[] types,
                         RequestOptions options) throws Exception;
public <T> RspList<T>
       callRemoteMethods(Collection<Address> dests, MethodCall method_call,
                         RequestOptions options) throws Exception;

public <T> T callRemoteMethod(Address dest,
                              String method_name, Object[] args, Class[] types,
                              RequestOptions options) throws Exception;
public <T> T callRemoteMethod(Address dest, MethodCall call,
                              RequestOptions options) throws Exception;
----

* The `callRemoteMethods()` (multicast) methods are invoked with a list of target
addresses. If null, the method will be invoked in all cluster nodes. Each call takes
the target members to invoke it on (`null` means invoke on all nodes), a method and a `RequestOptions` object.

** The method can be given as (1) the method name, (2) the arguments and (3) the argument types, or a
MethodCall (containing a `java.lang.reflect.Method` and argument) can be given instead.

* A `RspList` or a future to a RspList is returned.

* The `callRemoteMethod()` (unicast) methods take almost the same parameters, except
that there is only one destination address instead of a list.

* The `callRemoteMethod()` calls return the actual result (or type T), or throws an
exception if the method threw an exception on the target member.

* Reflection is used to find the correct method in the target node according to the method name and
number and types of supplied arguments. There is a runtime exception if a method cannot be resolved.



RpcDispatcher example
---------------------
[source,java]
----
public int print(int number) throws Exception {return number * 2;}  // <1>

RequestOptions opts=new RequestOptions(ResponseMode.GET_ALL, 5000); // <2>
JChannel channel=new JChannel();
RpcDispatcher disp=new RpcDispatcher(channel, this);   // <3>
channel.connect("RpcDispatcherTestGroup");
for(int i=0; i < 10; i++) {
    RspList rsp_list=disp.callRemoteMethods(null,      // <4>
                                            "print",
                                            new Object[]{i},
                                            new Class[]{int.class},
                                            opts);
    System.out.println("Responses: " + rsp_list);
}
----
<1> Define public method `print()`
<2> Define a `RequestOptions` object with mode=synchronous and a timeout of 5 seconds
<3> Create an `RpcDispatcher` over the channel, `this` means all methods to be invoked are in the same class
<4> Invoke the call on all cluster nodes (`null`). The method name is `"print"`, the actual argument is an array of one
element (`i`), and the formal parameters are defined with an array of class information. Finally, the RequestOptions instance
previously created is passed to the call.



Response filters
----------------
* Response filters allow application code to drop responses, or to return from a blocking call before ak responses
  have been received.
* The `RspFilter` interface looks as follows:
          
[source,java]
----
public interface RspFilter {
    boolean isAcceptable(Object response, Address sender);
    boolean needMoreResponses();
}      
----

* Method `isAcceptable()` is given a response value and the address of the member which sent
the response, and needs to decide whether the response is valid (returning true) or not
(returning false).
          
* Method `needMoreResponses()` determines whether a call is done or not.



Response filter example
-----------------------
The sample code below shows how to use a RspFilter:

[source,java]
----
RspFilter filter=new RspFilter() {
    int num=0;
    public boolean isAcceptable(Object response, Address sender) {
        boolean retval=(Integer)response > 1; // <1>
        if(retval)
            num++;
        return retval;
    }
    public boolean needMoreResponses() { 
        return num < 2;                       // <2>
    }
};

RequestOptions opts=RequestOptions.SYNC().setRspFilter(filter); // <3>
RspList rsps=disp.callRemoteMethods(null, "foo", null, null, opts);
----
<1> The response filter acepts all integer values that are greater than 1. All accepted values increment a counter.
<2> The call returns as soon as (1) it has received 2 valid responses or (2) the timeout elapsed or (3) it received responses
from all members.
<3> The RequestOptions object is passed the `RspFilter` instance.



Asynchronous calls with futures
-------------------------------
* When invoking a synchronous call, the calling thread is blocked until the response (or responses) has
  been received.

* A _future_ allows a caller to return immediately and grab the result(s) later.

[source,java]
----
public NotifyingFuture<RspList>
       callRemoteMethodsWithFuture(Collection<Address> dests, MethodCall method_call,
                                   RequestOptions options) throws Exception;
public <T> NotifyingFuture<T>
       callRemoteMethodWithFuture(Address dest, MethodCall call,
                                  RequestOptions options) throws Exception;
----

* A `NotifyingFuture` extends `java.util.concurrent.Future`, with its regular methods such as `isDone()`,
  `get()` and `cancel()`. This is shown in the following code:
            
[source,java]
----
Future<Integer> future=dispatcher.callRemoteMethodWithFuture(...); // <1>
int num=future.get(); // <2>
----
<1> Here we invoke a unicast method, which completes immediately, returning a future
<2> The `get()` blocks until the result is available




Asynchronous invocation in RpcDispatcher
----------------------------------------
* A method invoked in an RpcDispatcher is dispatched to application code
  by calling method handle from RequestHandler:

[source,java]
----
public interface RequestHandler {
    Object handle(Message msg) throws Exception;
}
----

* In the case of RpcDispatcher, the `handle()` method converts the message's contents into a method call,
  invokes the method against the target object and returns the result (or throws an exception). The return value
  of `handle()` is then sent back to the sender of the message.
        
* The invocation is _synchronous_, ie. done on the thread responsible for dispatching this
  particular message from the network up the stack all the way into the application. The thread is therefore
  _unusable_ for the duration of the method invocation.
        
* If the invocation takes a while, e.g. because locks are acquired or the application waits on some I/O, as
  the current thread is busy, another thread will be used for a different request message. This can quickly
  lead to the thread pool being exhausted or many messages getting queued if the pool has an associated queue.
        
* Therefore a new way of dispatching messages to the application was devised; the asynchronous invocation API:

[source,java]
----
public interface AsyncRequestHandler extends RequestHandler {
    void handle(Message request, Response response) throws Exception;
}
----

* Extending `RequestHandler`, `AsyncRequestHandler` adds an additional method taking a request message
  and a `Response` object. The request message contains the same information as before (e.g. a method call plus
  args). The `Response` argument is used to send a reply (if needed) at a later time, when processing is done.
        
[source,java]
----
public interface Response {
    void send(Object reply, boolean is_exception);
}    
----

* Response encapsulates information about the request (e.g. request ID and sender), and has method `reply()` to
  send a response. The `is_exception` parameter can be set to true if the reply is actually an exception, e.g.
  that was thrown when `handle()` ran application code.
        
* The advantage of the new API is that it can, but doesn't have to, be used asynchronously. The default
  implementation still uses the synchronous invocation style:

[source,java]
----
public void handle(Message request, Response response) throws Exception {
    Object retval=handle(request);
    if(response != null)
        response.send(retval, false);
}
----

* Method `handle()` is called, which synchronously calls into application code and returns a result, which is
  subsequently sent back to the sender of the request message.

* However, an application could subclass RpcDispatcher (as done in Infinispan), or it
could set a custom request handler via `setRequestHandler()`, and implement `handle()` by
dispatching the processing to a thread from a thread pool. The thread which guided the request message from
the network up to this point would be therefore immediately released and could be used for other messages.
The response would be sent whenever the invocation of application code is done, and thus the thread from
the thread pool would not be blocked on I/O, trying to acquire locks or anything else that blocks in
application code.
        
* To set the mode which is used, method `asyncDispatching(boolean)` can be used. This can be
  changed even at runtime, to switch between sync and async invocation style.

* Asynchrounous invocation is typically used in conjunction with an application thread pool. The application
  knows (JGroups doesn't) which requests can be processed in parallel and which ones can't. For example,
  all OOB calls could be dispatched directly to the thread pool, as ordering of OOB requests is not important,
  but regular requests should be added to a queue where they are processed sequentually.
        
* The main benefit here is that request dispatching (and ordering) is now under application control
  _if the application wants to do that_. If not, we can still use synchronous invocation.

* A good example where asynchronous invocation makes sense are replicated web sessions. If a cluster node A
  has 1000 web sessions, then replication of updates across the cluster generates messages from A. Because
  JGroups delivers messages from the _same_ sender _sequentially_, even
  updates to unrelated web sessions are delivered in strict order.

* With asynchronous invocation, the application could devise a dispatching strategy which assigns updates to
  different (unrelated) web sessions to any available thread from the pool, but queues updates to the same
  session, and processes those by the same thread, to provide ordering of updates to the same session. This
  would speed up overall processing, as updates to a web session 1 on A don't have to wait until all
  updates to an unrelated web session 2 on A have been processed.
