
Overview of the most common protocols
=====================================
:author: Bela Ban belaban@yahoo.com
:backend: deckjs
:deckjs_transition: fade
:navigation:
:deckjs_theme: web-2.0
:deckjs_transition: fade
:goto:
:menu:
:toc:
:status:

// Overview of the most common protocols. What does each protocol do and
// what are the attributes that most commonly need to be changed.


Transport protocols
-------------------
* A _transport protocol_ refers to the protocol at the bottom of the protocol stack which is
responsible for sending messages to and receiving messages from the network. There are a
number of transport protocols in JGroups. They are discussed in the following sections.
* A typical protocol stack configuration using UDP is shown below


udp.xml
-------

[source,xml]
----
<config>
    <UDP mcast_port="${jgroups.udp.mcast_port:45588}"
         ip_ttl="8"
         mcast_recv_buf_size="5M"
         mcast_send_buf_size="5M"
         enable_diagnostics="true"

         thread_pool.min_threads="2"
         thread_pool.max_threads="8"
         thread_pool.keep_alive_time="5000"/>

    <PING />
    <MERGE3 max_interval="30000" min_interval="10000"/>
    <FD_SOCK/>
    <FD_ALL/>
    <VERIFY_SUSPECT timeout="1500"  />
    <pbcast.NAKACK2 xmit_interval="1000"/>
    <UNICAST3 xmit_interval="1000"/>
    <pbcast.STABLE desired_avg_gossip="50000"
                   max_bytes="4M"/>
    <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
    <UFC max_credits="2M" min_threshold="0.4"/>
    <MFC max_credits="2M" min_threshold="0.4"/>
    <FRAG2 frag_size="60K"  />
    <pbcast.STATE_TRANSFER />
</config>
----


Protocols
---------

UDP: Transport protocol using IP multicasting to send messages to the entire cluster,
      or individual members. Other transports include `TCP`, `TCP_NIO2` and `TUNNEL`.

PING: Discovery protocol. It uses IP multicast (by default) to find initial members.
       Once found, the current coordinator can be determined and a JOIN request is sent
       to join the cluster.
                    
MERGE3: Will merge sub-clusters back into one cluster, kicks in after a network partition healed.

FD_SOCK: Failure detection based on sockets (in a ring form between members). Generates notifications
         if a member fails

FD_ALL: Failure detection based on heartbeats. Generates notifications if a member fails

VERIFY_SUSPECT: Double-checks whether a suspected member is dead,
                otherwise the suspicion generated from the protocol below is discarded

pbcast.NAKACK2: Ensures (a) message reliability and (b) FIFO order. Reliability guarantees that a message
                will be received. If not, the receiver(s) request retransmission. FIFO guarantees that
                all messages from sender P are received in the order in which P sent them

UNICAST3: Same as NAKACK for unicasts: messages from sender P will not be lost (retransmission if
           necessary) and will be in FIFO order (conceptually similar to TCP/IP)

pbcast.STABLE: Deletes messages that have been seen by all members

pbcast.GMS: Membership protocol. Responsible for joining/leaving members and installing new views.

UFC: Unicast Flow Control. Provides flow control between 2 members.

MFC: Multicast Flow Control. Provides flow control between a sender and all cluster members.
                    
FRAG2: Fragments large messages into smaller ones and reassembles them at the receiver.
       For multicast and unicast messages

STATE_TRANSFER: Ensures that state is correctly transferred from an existing member (usually the
                coordinator) to a new member.


Transport protocols (UDP, TCP, TCP_NIO2)
----------------------------------------
bind_addr:: Determines the network interface to bind to, e.g. `bind_addr=192.168.1.5`. The following values
are also recognized:
* `global`: picks a global IP address if available. If not, falls back to a `site-local` IP address
* `site_local`: picks a site local (non routable) IP address, e.g. from the +192.168.0.0+ or +10.0.0.0+ address range.
* `link_local`: picks a link-local IP address, from +169.254.1.0+ through +169.254.254.255+.
* `non_loopback`: picks _any_ non loopback address.
* `loopback`: picks a loopback address, e.g. +127.0.0.1+.
* `match-interface`: picks an address which matches a pattern against the interface name,
                  e.g. `match-interface:eth.\*`
* `match-host`: picks an address which matches a pattern against the host name,
             e.g. `match-host:linux.\*`
* `match-address`: picks an address which matches a pattern against the host address,
                e.g. `match-address:192.168.\*`

NOTE: A `bind_addr` value may consist of multiple comma-separated elements, e.g. +
`match-interface:eth0,match-interface:en0,site_local,loopback`. +
This will try to bind to an interface `eth0` if it finds one. If not, `en0` is tried, then a site-local address,
and finally the loopback interface (`127.0.0.1`). The iteration through the list stops as soon as a valid value
has been found.

bind_port:: The port to listen on. If not set, the port will be picked by the OS. If the port is in use,
            JGroups will increment it until it finds a free port. 
            Example: `bind_addr="10.5.5.5" bind_port="7800"` results in a node's address being `10.5.5.5:7800`.
            The second node started on the same host will use `10.5.5.5:7801`.

enable_diagnostics:: Opens a multicast port which `probe.sh` can use to fetch information from a given node.
                     The multicast address and port can be set with `diagnostics_addr` and `diagnostics_port`. 

Exercise: setting bind_addr
---------------------------
Try out picking various bind addresses, e.g.

`run.sh -Djgroups.bind_addr=BIND org.lab.ChatDemo -props config.xml -name A`

where `BIND` is one of the above values for `bind_addr`.


UDP
---
mcast_addr:: The multicast address to be used. If multiple clusters are running, use separate values for
             `mcast_addr` / `mcast_port` and cluster name (`JChannel.connect(cluster_name)`)

mcast_port:: The port to be used for multicasts.



TCPPING
-------
initial_hosts:: A list of _all_ members in a cluster, e.g. `192.168.1.1[7800],192.168.1.2[7800],192.168.1.3[7800]`
* Note that `bind_port` in the transport needs to be `7800`



FD_ALL
------
* Every node multicasts heartbeats at a given `interval` and collects heartbeats from other nodes, setting
  a timestamp for P when a heartbeat from P has been received
* Every `timeout_check_interval` the timestamps are checked for expiry, and expired members are suspected.

timeout:: Max time (in ms) after which a node is suspected if the associated timestamp hasn't been reset.

interval:: The interval (in ms) at which a node multicasts heartbeats

timeout_check_interval:: The interval (in ms) at which timestamps are check for expiry

msg_counts_as_heartbeat:: A message from P resets P's timestamp (if true)



GMS
---

join_timeout:: The max time (in ms) to try joining a cluster. If it elapses, a new attempt is started.


