
Overview of the most commonly used protocols
============================================
author: Bela Ban belaban@yahoo.com

Overview of the most common protocols. What does each protocol do and
what are the attributes that most commonly need to be changed.


Transport protocols
-------------------
*A _transport protocol_ refers to the protocol at the bottom of the protocol stack which is
responsible for sending messages to and receiving messages from the network. There are a
number of transport protocols in JGroups. They are discussed in the following sections.
* A typical protocol stack configuration using UDP is:

[source,xml]
----

<config xmlns="urn:org:jgroups"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
    <UDP
         mcast_port="${jgroups.udp.mcast_port:45588}"
         ucast_recv_buf_size="20M"
         ucast_send_buf_size="640K"
         mcast_recv_buf_size="25M"
         mcast_send_buf_size="640K"
         loopback="true"
         discard_incompatible_packets="true"
         max_bundle_size="64K"
         max_bundle_timeout="30"
         ip_ttl="${jgroups.udp.ip_ttl:2}"
         enable_diagnostics="true"

         thread_pool.enabled="true"
         thread_pool.min_threads="2"
         thread_pool.max_threads="8"
         thread_pool.keep_alive_time="5000"
         thread_pool.queue_enabled="true"
         thread_pool.queue_max_size="10000"
         thread_pool.rejection_policy="discard"

         oob_thread_pool.enabled="true"
         oob_thread_pool.min_threads="1"
         oob_thread_pool.max_threads="8"
         oob_thread_pool.keep_alive_time="5000"
         oob_thread_pool.queue_enabled="false"
         oob_thread_pool.rejection_policy="Run"/>

    <PING timeout="2000"
            num_initial_members="3"/>
    <MERGE3 max_interval="30000"
            min_interval="10000"/>
    <FD_SOCK/>
    <FD_ALL/>
    <VERIFY_SUSPECT timeout="1500"  />
    <BARRIER />
    <pbcast.NAKACK2 use_mcast_xmit="true"
                   retransmit_timeout="300,600,1200"
                   discard_delivered_msgs="true"/>
    <UNICAST3 timeout="300,600,1200"/>
    <pbcast.STABLE stability_delay="1000" desired_avg_gossip="50000"
                   max_bytes="4M"/>
    <pbcast.GMS print_local_addr="true" join_timeout="3000"
                view_bundling="true"/>
    <UFC max_credits="2M"
         min_threshold="0.4"/>
    <MFC max_credits="2M"
         min_threshold="0.4"/>
    <FRAG2 frag_size="60K"  />
    <pbcast.STATE_TRANSFER />
</config>
        
----

In a nutshell the properties of the protocols are:
    

UDP:: This is the transport protocol. It uses IP multicasting to send messages to the entire cluster,
      or individual nodes. Other transports include `TCP` and `TUNNEL`.
                    

PING:: This is the discovery protocol. It uses IP multicast (by default) to find initial members.
       Once found, the current coordinator can be determined and a unicast JOIN request will be sent
       to it in order to join the cluster.
                    

MERGE3:: Will merge sub-clusters back into one cluster, kicks in after a network partition healed.

FD_SOCK:: Failure detection based on sockets (in a ring form between members). Generates notification
          if a member fails
                    

FD / FD_ALL:: Failure detection based on heartbeat are-you-alive messages. Generates notification
              if a member fails

VERIFY_SUSPECT:: Double-checks whether a suspected member is really dead,
                 otherwise the suspicion generated from protocol below is discarded

BARRIER:: Needed to transfer state; this will block messages that modify the shared state until a
          digest has been taken, then unblocks all threads. _Not needed if no state transfer protocol is present._
                    

pbcast.NAKACK2:: Ensures (a) message reliability and (b) FIFO. Message reliability guarantees that a message
                 will be received. If not, the receiver(s) will request retransmission. FIFO guarantees that
                 all messages from sender P will be received in the order P sent them

UNICAST3:: Same as NAKACK for unicast messages: messages from sender P will not be lost (retransmission if
           necessary) and will be in FIFO order (conceptually the same as TCP in TCP/IP)

pbcast.STABLE:: Deletes messages that have been seen by all members (distributed message garbage collection)

pbcast.GMS:: Membership protocol. Responsible for joining/leaving members and installing new views.

UFC:: Unicast Flow Control. Provides flow control between 2 members.
                    

MFC:: Multicast Flow Control. Provides flow control between a sender and all cluster members.
                    

FRAG2:: Fragments large messages into smaller ones and reassembles them back at the receiver side. For both
        multicast and unicast messages 

STATE_TRANSFER:: Ensures that state is correctly transferred from an existing member (usually the
                 coordinator) to a new member.


Transport protocols (UDP, TCP)
------------------------------
bind_addr:: Determines the network interface to bind to, e.g. `bind_addr=192.168.1.5`. The following values
are also recognized:
* `global`: picks a global IP address if available. If not, falls back to a `site-local` IP address
* `site-local`: picks a site local (non routable) IP address, e.g. from the +192.168.0.0+ or +10.0.0.0+ address range.
* `link-local`: picks a link-local IP address, from +169.254.1.0+ through +169.254.254.255+.
* `non-loopback`: picks _any_ non loopback address.
* `loopback`: picks a loopback address, e.g. +127.0.0.1+.
* `match-interface`: picks an address which matches a pattern against the interface name,
                  e.g. +match-interface:eth.\*+
* `match-host`: picks an address which matches a pattern against the host name,
             e.g. +match-host:linux.\*+
* `match-address`: picks an address which matches a pattern against the host address,
                e.g. +match-address:192.168.\*+

bind_port:: The port to listen on. If not set, the port will be picked by the OS. If the port is in use,
            JGroups will increment it until it finds a free port. 
            Example: `bind_addr="10.5.5.5" bind_port="7800"` results in a node's address being `10.5.5.5:7800`.
            The second node started on the same host will use `10.5.5.5:7801`.

enable_diagnostics:: Opens a multicast port which `probe.sh` can use to fetch information from a given node.
                     The multicast address and port can be set with `diagnostics_addr` and `diagnostics_port`. 



UDP
---
mcast_addr:: The multicast address to be used. If multiple clusters are running, use separate values for
             `mcast_addr` / `mcast_port` and cluster name (`JChannel.connect(cluster_name)`)

mcast_port:: The port to be used for multicasts.



TCPPING
-------
initial_hosts:: A list of _all_ members in a cluster, e.g. `192.168.1.1[7800],192.168.1.2[7800],192.168.1.3[7800]`

FD
--
All members form a logical circle, where each member pings the member to its right for liveness. Example: in a
cluster `{A,B,C}`, A pings B, B pings C and C pings A.

timeout:: The interval (ms) at which heartbeats are sent to the neighbor to the right.

max_tries:: The max number of missed heartbeats for a node to get suspected. So if `timeout=3000` and
`max_tries=3`, then it will take 9 seconds for A to suspect B if A didn't receive any heartbeats (or messages)
from B in that time frame.

msg_counts_as_heartbeat:: If heartbeats are missed, but messages are received from B, B won't get suspected by
A (if true).



FD_ALL
------
Every node multicasts heartbeats at a given `interval`. Every node collect heartbeats from all other nodes and
sets a timestamp for P when a heartbeat from P has been received. Every `timeout_check_interval` the timestamps
are checked if they are expired, and expired members are suspected. 

timeout:: Max time (in ms) after which a node is suspected if the associated timestamp hasn't been reset.

interval:: The interval (in ms) at which a node multicasts heartbeats

timeout_check_interval:: The interval (in ms) at which timestamps are check for expiry

msg_counts_as_heartbeat:: A message from P resets P's timestamp (if true)



GMS
---

join_timeout:: The max time (in ms) to try joining a cluster. If it elapses, a new attempt is started.


