

Status JGroups 2012-2014
========================

* Status JGroups 2012-2013
** 3.2, 3.3, 3.4, 3.5
* Work planned for 2014 and beyond
** 4.0
* Large scale
** 2000+ nodes
** Google Compute Engine


JGroups 3.2
-----------
* Used in EAP 6.2.0
* Current version: 3.2.12.Final



RELAY2: multi-site clustering
-----------------------------

* https://issues.jboss.org/browse/JGRP-1433[JGRP-1433],
  http://issues.jboss.org/browse/JGRP-1401[JGRP-1401],
  https://issues.jboss.org/browse/JGRP-1521[JGRP-1521],
  https://issues.jboss.org/browse/JGRP-1519[JGRP-1519],
  https://issues.jboss.org/browse/JGRP-1525[JGRP-1525]

* Provides clustering between multiple sites
** Successor to RELAY (which allowed for only 2 sites)
* RELAY2 is added to the of the stack and relays both multicast and
  unicast messages between sites (local clusters) 
* For documentation go to
  http://www.jgroups.org/manual-3.x/html/user-advanced.html#Relay2Advanced



I8N logging
-----------
* https://issues.jboss.org/browse/JGRP-1475[JGRP-1475]
* Use of ResourceBundles to internationalize certain warn and error
  messages
* The +JGroups/conf/jg-messages*.properties+ files contain the
  translations
* Currently, only German is supported, but support for any language
  can be added easily, and without recompilation, e.g. by adding
  +jg-messages_fr.properties+ (for French) to the classpath


Suppress identical log warnings
-------------------------------
* https://issues.jboss.org/browse/JGRP-1518[JGRP-1518]
* Sometimes we get a lot of log messages about the same problem,
  e.g. messages from a non-member, from a different cluster or from a
  member running a different version of JGroups 
** If we get 20'000 messages from a non-member, we'd log 20'000 warnings...
* We can now suppress indentical warnings for a given period of time
  (60s by default), so the logs don't get blown up beyond proportion






JGroups 3.3
-----------

Message batching
----------------
* https://issues.jboss.org/browse/JGRP-1564[JGRP-1564],
  https://issues.jboss.org/browse/JGRP-1581[JGRP-1581] 
* On the receiver, message bundles received are passed up together, in the form of message batches. The advantage is
  that the costs for passing up messages is amortized, as (e.g.) locks
  are acquired only once per batch instead of once per message.
* Example:
[source,java]
    public void up(MessageBatch batch) {
        for(Message msg: batch) {
            FragHeader hdr=(FragHeader)msg.getHeader(this.id);
            if(hdr != null) { // needs to be defragmented
                Message assembled_msg=unfragment(msg,hdr);
                if(assembled_msg != null)
                    batch.replace(msg, assembled_msg);
                else
                    batch.remove(msg);
            }
        }
        if(!batch.isEmpty())
            up_prot.up(batch);
    }




Async Invocation API
--------------------
* https://issues.jboss.org/browse/JGRP-1587[JGRP-1587]
* This allows the recipient of a message in MessageDispatcher or RpcDispatcher to make the delivering thread return
  immediately (making it available for other requests) and to send the
  response later
* The advantage is that it is the application which now decides how to
  deliver messages (e.g. sequentially or in parallel), and not JGroups 
* Documentation is here: http://www.jgroups.org/manual-3.x/html/user-building-blocks.html#AsyncInvocation.


UNICAST3
--------
* https://issues.jboss.org/browse/JGRP-1589[JGRP-1589]
* New unicast protocol which combines the advantages of UNICAST and UNICAST2. UNICAST3 has the immediately delivery
  characteristics of UNICAST and the speed of UNICAST2
* It is the default unicast protocol in 3.3
* For details: https://github.com/belaban/JGroups/blob/master/doc/design/UNICAST3.txt


New thread pool for JGroups-internal messages only
--------------------------------------------------
* https://issues.jboss.org/browse/JGRP-1599[JGRP-1599]
* Added a new thread pool to be used by JGroups only
  (+internal_thread_pool.enabled=true|false+)
* This prevents OOB messages sent by applications to clog the pool and slow internal
  messages such as heartbeats or flow control credits down 


RELAY2 fixes and enhancements
-----------------------------
* https://issues.jboss.org/browse/JGRP-1517[JGRP-1517],
  https://issues.jboss.org/browse/JGRP-1528[JGRP-1528], 
  https://issues.jboss.org/browse/JGRP-1542[JGRP-1542],
  https://issues.jboss.org/browse/JGRP-1543[JGRP-1543],
  https://issues.jboss.org/browse/JGRP-1547[JGRP-1547],
  https://issues.jboss.org/browse/JGRP-1629[JGRP-1629],
  https://issues.jboss.org/browse/JGRP-1623[JGRP-1623]
* When a coordinator crashes, messages are buffered until the new
  coordinator takes over. JGRP-1517 ensures that resending the
  buffered messages occurs before new messages are sent
* JGRP-1528 forwards messages in batches rather than individually, not blocking senders
* JGRP-1542 copies flags of relayed messages, so flags such as OOB are preserved.
* JGRP-1543 provides site-unreachable notifications, so callers know that a site is unreachable.
* JGRP-1547 provides timing stats for forwarding of messages
* JGRP-1629 adds the ability to insert a RELAY2 protocol to an already connected stack



PDC
---
* https://issues.jboss.org/browse/JGRP-1541[JGRP-1541]
* A new protocol to cache discovery responses on disk, suitable for use with (e.g.) TCPPING.


SUPERVISOR
----------
* https://issues.jboss.org/browse/JGRP-1557[JGRP-1557]
* New protocol which can auto-correct (or log) things at runtime, based on rules


Log4j2 is now the default logging framework used
------------------------------------------------
* https://issues.jboss.org/browse/JGRP-1585[JGRP-1585]
* Log4j is still supported, but log4j2 is preferred (more efficient and less blocking)


Pick NIC based on pattern matching
----------------------------------
* https://issues.jboss.org/browse/JGRP-1606[JGRP-1606]
* E.g. +UDP.match_interface="eth*"+


MPerfRpc
--------
* https://issues.jboss.org/browse/JGRP-1625[JGRP-1625]
* New performance test for RPCs



NAKACK2: unneeded retransmissions
---------------------------------
* https://issues.jboss.org/browse/JGRP-1539[JGRP-1539]
* The retransmit algorithm in NAKACK2 would sometimes ask the sender
  to retransmit messages which were received a few ms later
* This created unnecessary traffic
* The adopted fix reduces the number of retransmits.


TP: simplified message bundler
------------------------------
* https://issues.jboss.org/browse/JGRP-1540[JGRP-1540]
* The new bundler (enabled by default) is simpler and more efficient than the previous ones
* It queues messages until a max size has been reached, or until no more messages are
  available in the queue, and then sends the queued messages as a message bundle
* The advantage is that we now don't need the +DONT_BUNDLE+ message flag anymore, as either
  the bundle will fill quickly, or no more message is available and so we send the
  message(s) quickly
* This is important for sync RPCs.
* Note that OOB messages are now bundled, too, so if bundling is to be avoided, the
  +DONT_BUNDLE+ flag has to be used 


Speed improvements in FORWARD_TO_COORD and SEQUENCER
----------------------------------------------------
* https://issues.jboss.org/browse/JGRP-1544[JGRP-1544],
  https://issues.jboss.org/browse/JGRP-1604[JGRP-1604]


TCP: better handling of concurrent connections
----------------------------------------------
* https://issues.jboss.org/browse/JGRP-1549[JGRP-1549]


New Timer implementation
------------------------
* https://issues.jboss.org/browse/JGRP-1553[JGRP-1553]
* Efficient, faster and simpler than the previous implementations
* This is the default now


STABLE: reduction of time until stability
-----------------------------------------
* https://issues.jboss.org/browse/JGRP-1570[JGRP-1570],
  https://issues.jboss.org/browse/JGRP-1595[JGRP-1595]
* With increasing cluster size, it took much longer to achieve stability, as the time to
  send out a STABLE message was scaled with the cluster size
* This is not done anymore, and we have now by default enabled
  +send_stable_msgs_to_coord_only+
* Members send their STABLE messages to the current coordinator only instead of
  multicasting them to all members (cuts down on traffic) 







JGroups 3.4
-----------


JGroups 3.4.1
-------------
* Used in EAP 7.x (not yet released)
* Current version: 3.4.2.Final



JGroups 3.4.2
-------------


JGroups 3.5
-----------


JGroups 4.0
-----------


