
= Status JGroups 2018
:author: Bela Ban belaban@mailbox.org
:backend: deckjs
:deckjs_transition: fade
:navigation:
:deckjs_theme: web-2.0
:goto:
:menu:
:toc:
:status:







= JGroups 4.0.8

* Multiple discovery protocols: https://issues.jboss.org/browse/JGRP-2224
[source.xml]
----
   <TCP ... />
   <TCPPING initial_hosts="127.0.0.1[7800]" port_range="0"/>
   <PING />
   <MPING/>
   <FILE_PING/>
   <MULTI_PING async_discovery="true"/>
   <MERGE3/>
   ...
----
* Will be changed, so that multiple discovery protocols can be configured without the need for `MULTI_PING` to
be present


= JGroups 4.0.10
* `INJECT_VIEW`: protocol to inject random views (https://issues.jboss.org/browse/JGRP-2243)


= JGroups 4.0.12
* `ASYM_ENCRYPT` simplifications / bugfixes:
** https://issues.jboss.org/browse/JGRP-2270
** https://issues.jboss.org/browse/JGRP-2272
** https://issues.jboss.org/browse/JGRP-2273
** https://issues.jboss.org/browse/JGRP-2274
** https://issues.jboss.org/browse/JGRP-2275
* `MERGE3`: a dead merge leader never leads to a merge (https://issues.jboss.org/browse/JGRP-2276)
* `TUNNEL`: bundling is now supported (https://issues.jboss.org/browse/JGRP-2255)
* `RELAY2`: notifications when someone becomes site master, or ceases to be site master
  (https://issues.jboss.org/browse/JGRP-2267)

= JGroups 4.0.13
* `CENTRAL_LOCK2`: new locking protocol that doesn't use a backup lock manager, but reconciliation when the coordinator
  (lock manager) crashes or leaves
** Less communication during regular operation, but chatty during coordinator crash
** https://issues.jboss.org/browse/JGRP-2249
** Design doc: https://github.com/belaban/JGroups/blob/master/doc/design/CENTRAL_LOCK2.txt

* Change the way a coordinator leaves gracefully
** Same code is now used to handle coord crashes and leaves
** Instead of installing the 'last view', a leaving coord asks the next-in-line to do that
** https://issues.jboss.org/browse/JGRP-2277

* Asynchronous `MERGE3`
** Uses `FIND_MBRS_ASYNC` event to asynchronously do discovery
** Callback is called on _every response_
** Fixes https://issues.jboss.org/browse/JGRP-2281


= JGroups 4.0.16
* Fix for JGRP-2277: graceful leave of coord and next-in-line(s) leaves the cluster with incorrect views
** https://issues.jboss.org/browse/JGRP-2293

* Discovery protocol for members in the same process
** Replacement for `TEST_PING`
** Not the same as `SHARED_LOOPBACK_PING` (which can only be used with `SHARED_LOOPBACK`)
** https://issues.jboss.org/browse/JGRP-2284



= JGroups 5.0

== API changes
* `Message` is now an interface
* Different implementations such as `BytesMessage`, `ObjectMessage`, `NioMessage` etc
** Every message still has a destination and sender address, headers and flags
* Ability to create and register own message types

== MessageFactory
[source,java]
----
public interface MessageFactory {

    /**
     * Creates a message based on the given ID
     * @param id The ID
     * @param <T> The type of the message
     * @return A message
     */
    <T extends Message> T create(byte id);

    /**
     * Registers a new creator of messages
     * @param type The type associated with the new payload.
     * @param generator The creator of the payload associated with the given type
     */
    void register(byte type, Supplier<? extends Message> generator);
}
----
* The message factory can be set and retrieved from the transport with `get/setMessageFactory()`

== Message implementations

=== BytesMessage
* Equivalent to old `Message`: has a byte array, an offset and a length
* JOL shows exactly the same memory layout as before:

----
[belasmac] /Users/bela$ jol-size.sh org.jgroups.BytesMessage

org.jgroups.BytesMessage object internals:
 OFFSET  SIZE     TYPE DESCRIPTION                    VALUE
      0     4          (object header)                ...
      4     4          (object header)                ...
      8     4          (object header)                ...
     12     2    short BaseMessage.flags              0
     14     1     byte BaseMessage.transient_flags    0
     15     1          (alignment/padding gap)        N/A
     16     4  Address BaseMessage.dest_addr          null
     20     4  Address BaseMessage.src_addr           null
     24     4 Header[] BaseMessage.headers            [null, null, null, null]
     28     4      int BytesMessage.offset            0
     32     4      int BytesMessage.length            0
     36     4   byte[] BytesMessage.buf               null
Instance size: 40 bytes
Space losses: 1 bytes internal + 0 bytes external = 1 bytes total
----
* This is still the most frequently used message used internally by JGroups (followed by `EmptyMessage`)

==== Allocation and performance
* 8 nodes, UPerf with UDP, 80% reads / 20% writes
* Performance is the same as with the old `Message` (~42'000/sec/node)
* Allocation
** TLABs: 7.4GB (master: 7.32), allocation rate TLABs: 126.33MB/sec (master: 124.9)
** Objects: 33.39GB (master: 37.68), allocation rate: 569.98kB/sec (master: 643.08kB/sec)


=== EmptyMessage
* No payload
* Used by JGroups to send messages which contain only flags and headers
* Compact size:
----
[belasmac] /Users/bela$ jol-size.sh org.jgroups.EmptyMessage

org.jgroups.EmptyMessage object internals:
 OFFSET  SIZE     TYPE DESCRIPTION                    VALUE
      0     4          (object header)                ...
      4     4          (object header)                ...
      8     4          (object header)                ...
     12     2    short BaseMessage.flags              0
     14     1     byte BaseMessage.transient_flags    0
     15     1          (alignment/padding gap)        N/A
     16     4  Address BaseMessage.dest_addr          null
     20     4  Address BaseMessage.src_addr           null
     24     4 Header[] BaseMessage.headers            [null, null, null, null]
     28     4          (loss due to the next object alignment)
Instance size: 32 bytes
Space losses: 1 bytes internal + 4 bytes external = 5 bytes total
----

=== NioMessage

=== NioDirectMessage

=== ObjectMessage

=== ObjectSerializable


=== FragmentedMessage
