
= Status JGroups 2019
:author: Bela Ban belaban@mailbox.org
:backend: deckjs
:deckjs_transition: fade
:navigation:
:deckjs_theme: web-2.0
:goto:
:menu:
:toc:
:status:





== JGroups 4.0.17
* Concurrent leaving of multiple members needs failure detection to establish correct views
* Example: {A,B,C,D,E}: A, B and C leave at the same time (*gracefully*)
* This is important in Kubernetes, when clusters are scaled down
** Default is 1 at a time, but user can configure this
* JIRA: https://issues.jboss.org/browse/JGRP-2293



== JGroups 4.0.18
* No issues, but released because 4.0.17 was compiled with Java 11


== JGroups 4.0.19
* Concurrent leaving fails with ASYM_ENCRYPT
** Required a change in key exchange code: from pull- to pish-style
  (https://github.com/belaban/JGroups/blob/master/doc/design/ASYM_ENCRYPT.txt)
** JIRA: https://issues.jboss.org/browse/JGRP-2297


== JGroups 4.0.20
* Backport of https://issues.jboss.org/browse/JGRP-2350, https://issues.jboss.org/browse/JGRP-2354

== JGroups 4.0.21
* Route list can be empty
** https://issues.jboss.org/browse/JGRP-2359


== JGroups 4.1.0
*  Support for compiling to GraalVM native images
** Changed code to support creating channels (via XML) at _build time_ or (programmatically) _at run time_
** New, non-reflective, probe handler: https://issues.jboss.org/browse/JGRP-2337
** Non-reflective `RpcDispatcher`: https://issues.jboss.org/browse/JGRP-2338
** Recently added support for `UDP` (IP multicasting)
** Blog: http://belaban.blogspot.com/2019/07/compiling-jgroups-to-native-code-with.html
** https://issues.jboss.org/browse/JGRP-2332

* Quarkus extension
** Extension https://github.com/jgroups-extras/quarkus-jgroups
** Can be used via `@Inject JChannel channel`
*** Sample: https://github.com/jgroups-extras/quarkus-jgroups-chat
** `application.properties` defines config:
[source]
----
quarkus.channel.config=chat-tcp.xml
quarkus.channel.cluster=quarkus-jgroups-chat
quarkus.channel.bind_addr=192.168.1.105
# quarkus.channel.initial_hosts=192.168.1.105[7800]

quarkus.log.level=WARN
quarkus.log.category."org.jgroups.quarkus.extension".level=TRACE
# quarkus.log.category."org.jgroups".level=TRACE
quarkus.log.category."org.jgroups.protocols.TCP".level=OFF
----

* Probe: add support for fetching data via `TCP`
** Useful with initial GraalVM port (only `TCP` was available at that time)
** https://issues.jboss.org/browse/JGRP-2336

* Wireshark / tshark / tcpdump support
** `ParseMessage` can now parse PCAP(.ng) files directly
** Videos: http://belaban.blogspot.com/2019/06/network-sniffing.html
** Doc: http://www.jgroups.org/manual4/index.html#_analyzing_wire_format_packets
** https://issues.jboss.org/browse/JGRP-2311

* Changed the way IPv4 or IPv6 addresses are resolved
** Scan the transport for explicit addresses, to see which stack (4 or 6) should be used
** https://issues.jboss.org/browse/JGRP-2343

* Signature change: `writeTo()`/`readFrom()` now throw `CNFE`/`IOException` instead of `Exception`
** Requires changes to code that uses serialization (e.g. headers)
** https://issues.jboss.org/browse/JGRP-2242


== JGroups 4.1.1
* Merging fails when `MULTI_PING` is in the stack (regression)
** https://issues.jboss.org/browse/JGRP-2349

* Closing of a blocked TCP connection failed
** `ifcfg eth0 down`
** https://issues.jboss.org/browse/JGRP-2350

* ForkChannel does not receive SITE_UNREACHABLE events
** https://issues.jboss.org/browse/JGRP-2354



== JGroups 4.1.2
* TCP_NIO2 fails under Java 8
** API incompatibility (`ByteBuffer.flip()`?)
** https://issues.jboss.org/browse/JGRP-2355


* LockService bugs
** https://issues.jboss.org/browse/JGRP-2360
** https://issues.jboss.org/browse/JGRP-2299
** https://issues.jboss.org/browse/JGRP-2364



== JGroups 4.1.3
* `ASYM_ENCRYPT`: removed option to encrypt entire message (including headers)
** Replaced by separate protocol: `SERIALIZE`
*** Not recommended: very costly
** https://issues.jboss.org/browse/JGRP-2273

* Deprecated some `AUTH` tokens
** `AUTH` should not be used for authentication anyway
** Use `ASYM_ENCRYPT` with `SSL_KEY_EXCHANGE` (uses SSL sockets to exchange shared group key)
** https://issues.jboss.org/browse/JGRP-2368

* `LOCAL_PING`: discovery protocol for members in the same process
** Contrary to `SHARED_LOOPBACK_PING` (which requires `SHARED_LOOPBACK` as transport), `LOCAL_PING`
   can use *any* transport
** Recent change (https://issues.jboss.org/browse/JGRP-2395) never creates any merging on concurrent startup
*** Ditto for `SHARED_LOOPBACK_PING`
** https://issues.jboss.org/browse/JGRP-2284

* `RELAY2` (cross-site): site-up or site-down is called in *all* members, not just site masters
** https://issues.jboss.org/browse/JGRP-2303

* Probe now handles multiple protocols of the same type in the same stack:
[code,xml]
----
<UDP/>
<PING/>
<FRAG2 id="350".../>
...
<GMS/>
<FRAG2.../>
----
** https://issues.jboss.org/browse/JGRP-2331




== JGroups 4.1.4
* `SSL_KEY_EXCHANGE` fixes
** https://issues.jboss.org/browse/JGRP-2370
** https://issues.jboss.org/browse/JGRP-2371
** https://issues.jboss.org/browse/JGRP-2373



== JGroups 4.1.5
* Support for `UDP:PING` on GraalVM
** IP multicasting is supported by GraalVM 19.2.1 now
** This also applies to diagnostics / probe (which use IP multicasting by default)
** https://issues.jboss.org/browse/JGRP-2344

* Optimization in UNICAST3 to make graceful leaves faster
** From ~500 ms (`xmit_interval`) to a few ms
** Speeds up concurrent graceful leaves (JGRP-2293)
** https://issues.jboss.org/browse/JGRP-2327

* Concurrent discovery fails
** When `num_discovey_runs` > 1
** https://issues.jboss.org/browse/JGRP-2375




== JGroups 4.1.6
* Messages from a non-member caused endless FD_ALL warnings
** https://issues.jboss.org/browse/JGRP-2387

* Support for encryption ciphers that require an initialization vector
** https://issues.jboss.org/browse/JGRP-2386




== JGroups 4.1.7
* MulticastSocket bind in DiagnosticsHandler failed on Windows
** Regression caused by GraalVM support (JGRP-2344)
** https://issues.jboss.org/browse/JGRP-2391


== JGroups 4.1.8
* Support for concurrent startup in `LOCAL_PING` and `SHARED_LOOPBACK_PING`
** Produces no merging at all
** https://issues.jboss.org/browse/JGRP-2395

* MPING: issue with creation of MulticastSocket
** https://issues.jboss.org/browse/JGRP-2397

* JMX issues
** https://issues.jboss.org/browse/JGRP-2394
** https://issues.jboss.org/browse/JGRP-2393







== JGroups 5.0

== API changes
* In 4.x, Message was a *class* accepting only *byte arrays* as payload
* In 5.0, `Message` is now an *interface*
* Implementations accept many different payloads, e.g. byte arrays, objects, NIO ByteBuffers
** Different implementations such as `BytesMessage`, `ObjectMessage`, `NioMessage` etc
* Ability to write own message types
* This is WIP, will become `master` soon (current master will become `4.x` branch)
* Subsequent releases (`5.1`, `5.2`...) will contain new functionality, but no API changes

* `Message`:

[source,java]
----
public interface Message extends SizeStreamable, Constructable<Message> {
    Supplier<Message>             create();

    Address                       getDest();
    <T extends Message> T         setDest(Address new_dest);

    Address                       getSrc();
    <T extends Message> T         setSrc(Address new_src);

    <T extends Message> T         putHeader(short id, Header hdr);
    <T extends Header> T          getHeader(short id);

    <T extends Message> T         setFlag(Flag... flags);

    <T extends Message> T         copy(boolean copy_payload, boolean copy_headers);

    boolean                       hasPayload();

    boolean                       hasArray();
    byte[]                        getArray();
    <T extends Message> T         setArray(byte[] b, int offset, int length);

    int                           getOffset();
    int                           getLength();

    <T extends Object> T          getObject();
    <T extends Message> T         setObject(Object obj);

    int                           size();
}
----


== MessageFactory
[source,java]
----
public interface MessageFactory {
    <T extends Message> T create(byte id);

    void register(byte type, Supplier<? extends Message> generator);
}
----
* The message factory can be set and retrieved from the transport with `get/setMessageFactory()`

== Message implementations

=== BytesMessage
* Equivalent to old `Message`: has a byte array, an offset and a length
* JOL shows exactly the same memory layout as before:

----
[belasmac] /Users/bela$ jol-size.sh org.jgroups.BytesMessage

org.jgroups.BytesMessage object internals:
 OFFSET  SIZE     TYPE DESCRIPTION                    VALUE
      0     4          (object header)                ...
      4     4          (object header)                ...
      8     4          (object header)                ...
     12     2    short BaseMessage.flags              0
     14     1     byte BaseMessage.transient_flags    0
     15     1          (alignment/padding gap)        N/A
     16     4  Address BaseMessage.dest_addr          null
     20     4  Address BaseMessage.src_addr           null
     24     4 Header[] BaseMessage.headers            [null, null, null, null]
     28     4      int BytesMessage.offset            0
     32     4      int BytesMessage.length            0
     36     4   byte[] BytesMessage.buf               null
Instance size: 40 bytes
Space losses: 1 bytes internal + 0 bytes external = 1 bytes total
----
* This is still the most frequently used message used internally by JGroups (followed by `EmptyMessage`)
* Change: from `new Message()` -> `new BytesMessage()`


==== Example
* Old:

[source,java]
----
Message msg=new Message(null, "hello world".getBytes());
channel.send(msg);
----

* New:

[source,java]
----
Message msg=new BytesMessage(null, "hello world".getBytes());
channel.send(msg);
----

* Message reception:

[source,java]
----
public void receive(Message msg) {
    BytesMessage m=(BytesMessage)msg; // if you know you're sending only BytesMessages
    // or use the generic methods (might throw exceptions though)
    String s=new String(msg.getArray(), msg.getOffset(), msg.getLength());
}
----



==== Allocation and performance
* 8 nodes, UPerf with UDP, 80% reads / 20% writes
* Performance is the same as with the old `Message` (~42'000/sec/node)
* Allocation
** TLABs: 7.4GB (master: 7.32), allocation rate TLABs: 126.33MB/sec (master: 124.9)
** Objects: 33.39GB (master: 37.68), allocation rate: 569.98kB/sec (master: 643.08kB/sec)


=== EmptyMessage
* No payload
* Example: leave request
* Used by JGroups to send messages which contain only flags and headers
* Compact size:
----
[belasmac] /Users/bela$ jol-size.sh org.jgroups.EmptyMessage

org.jgroups.EmptyMessage object internals:
 OFFSET  SIZE     TYPE DESCRIPTION                    VALUE
      0     4          (object header)                ...
      4     4          (object header)                ...
      8     4          (object header)                ...
     12     2    short BaseMessage.flags              0
     14     1     byte BaseMessage.transient_flags    0
     15     1          (alignment/padding gap)        N/A
     16     4  Address BaseMessage.dest_addr          null
     20     4  Address BaseMessage.src_addr           null
     24     4 Header[] BaseMessage.headers            [null, null, null, null]
     28     4          (loss due to the next object alignment)
Instance size: 32 bytes
Space losses: 1 bytes internal + 4 bytes external = 5 bytes total
----

==== Example

[source,java]
----
// GMS:
Message msg=new EmptyMessage(address).setFlag(OOB, INTERNAL)
              .putHeader(gms.getId(), new GmsHeader(LEAVE_RSP));
channel.send(msg);
----


=== NioMessage
* Has a (heap-based or direct-memory) `ByteBuffer` as payload
* On serialization (in the transport, at send time), the contents of the byte buffer are written to the
  output stream directly, no copying
* This avoids the conversion of `ByteBuffer` into a byte array, which was passed to the constructor of the
  old `Message`, eliminating a byte array allocation
* For off-heap ByteBuffers, we need a transfer buffer as there is no way to transfer the contents of a
  `ByteBuffer` directly to an output stream; once we have a transport that directly supports ByteBuffers,
  we can change this

==== Reading a direct NioMessage from the network
* There's an option (`use_direct_memory_for_allocations`) to use direct (off-heap)memory when reading,
  otherwise heap memory is used

==== Pluggable memory allocation?
* Memory allocation should probably be pluggable
* If a memory pool is to be used, we probably need ref-counting `Message`
** JGroups can only release in `NAKACK2` or `UNICAST3`


==== Example
[source,java]
----
byte[] array="hello world".getBytes();
NioMessage msg=new NioMessage(null, ByteBuffer.wrap(array));
channel.send(msg);
----




=== ObjectMessage
* Has an object as payload
* The object has to implement `SizeStreamable`:
[source,java]
----
public interface SizeStreamable extends Streamable {
    /** Returns the size (in bytes) of the marshalled object */
    int serializedSize();
}
----

[source,java]
----
public interface Streamable {
    void writeTo(DataOutput out) throws IOException;
    void readFrom(DataInput in)  throws IOException, ClassNotFoundException;
}
----
* Method `serializedSize()` must give the *exact number of bytes* when the object is marshalled
** This might be changed with https://issues.jboss.org/browse/JGRP-2289
* For fragmentation, if this method is incorrect and returns a value that's too low, an `ObjectMessage` may not get
fragmented, leading to possible size problems at the transport (e.g. UDP max datagram packet size of 65k).
* So, once JGRP-2289 is in place, it is better to return a size that errs on the side of too big rather than too small
* The transport calls `Streamable.writeTo(DataOutput)` when the `ObjectMessage` is sent to the network
* The transport calls `Streamable.readFrom(DataInput)` to create the `ObjectMessage` when received from the network

==== Example
[source,java]
----
Person p=new Person("Bela Ban", 322649, array); // Person implements SizeStreamable
Message msg=new ObjectMessage(dest, p);
channel.send(p);
----

=== ObjectMessageSerializable
* Subclass of `ObjectMessage`, but the payload (`Object`) does not have to implement any interface
* To be used when we have an object whose size we don't know
* The object is serialized into a byte array which is stored along with the object
** This is done just-in-time (e.g. on `getLength()`)
* The byte array is sent to the network
* Use `ObjectMessage` when possible


=== CompositeMessage
* Contains multiple messages
** Use case: send an NIO ByteBuffer and a byte[] array
** Previously, one would have had to create a byte[] array with space for both and then copy both
   into the byte array, and pass the byte array to the Message constructor
* Messages can have different types
* All messages have to have the same destination
* Similar to `MessageBatch` (for sending)
* Not sure this is useful

==== Example
[source,java]
----
CompositeMessage msg=new CompositeMessage(null, new EmptyMessage(null));
IntStream.of(10000, 15000, 5000).forEach(n -> msg.add(new BytesMessage(null, new byte[n])));
Person p=new Person("Bela Ban", 53, array);
msg.add(new ObjectMessageSerializable(null, p));
msg.add(new NioMessage(null, ByteBuffer.wrap(array)));
msg.add(new NioMessage(null, Util.wrapDirect(array)).useDirectMemory(false));
channel.send(msg);
----


=== FRAG4
* Use this protocol with `ObjectMessage`, `CompositeMessage` or `NioMessage`
* Or else (with `FRAG2` and `FRAG3`) we have superfluous marshalling of the object into a byte array
  (1 unneeded byte array allocation)
* `FRAG4` creates N `FragmentedMessage` instances, each with an offset and length, and a reference to the original
  message
* When serialized, the `FragmentedMessage` uses a `PartialOutputStream` to marshal only the subset of the original
  output stream between offset and length to the output stream



=== Misc
* More predefined message types? `IntMessage`, `LongMessage`
* Remove `dest` field from `BaseMessage`?
* Message without headers?
* What else can be removed?
* Breakout session: reduce memory allocation in Infinispan when sending commands
** `EmptyMessage`, `ObjectMessage`, `NioMessage`?


=== Other stuff in 5.0
* Multiple transports (`UDP` and `TCP`)?
** https://issues.jboss.org/browse/JGRP-1424
* RDMA transport (project Panama): https://issues.jboss.org/browse/JGRP-1680
* Default bundler (https://issues.jboss.org/browse/JGRP-1997)
* JDK 11
* Make TCP_NIO2 the default transport (currently, TCP is faster than TCP_NIO2)
** https://issues.jboss.org/browse/JGRP-2108
* Multiple discovery protocols without `MULTI_PING` (https://issues.jboss.org/browse/JGRP-2230)
* Handle ObjectMessage with incorrect size: https://issues.jboss.org/browse/JGRP-2285 and
  https://issues.jboss.org/browse/JGRP-2289
* Add TLS for TCP and TCP_NIO2: https://issues.jboss.org/browse/JGRP-2374

=== Roadmap after 5.0
* Let 5.0 bake for a while to see whether the API is OK
* Work with Infinispan team to port to 5.0 may also require some changes
* New functionality in minor releases (no API changes)
