
= Status JGroups 2018
:author: Bela Ban belaban@mailbox.org
:backend: deckjs
:deckjs_transition: fade
:navigation:
:deckjs_theme: web-2.0
:goto:
:menu:
:toc:
:status:







= JGroups 4.0.8

* Multiple discovery protocols: https://issues.jboss.org/browse/JGRP-2224
[source.xml]
----
   <TCP ... />
   <TCPPING initial_hosts="127.0.0.1[7800]" port_range="0"/>
   <PING />
   <MPING/>
   <FILE_PING/>
   <MULTI_PING async_discovery="true"/>
   <MERGE3/>
   ...
----
* Will be changed, so that multiple discovery protocols can be configured without the need for `MULTI_PING` to
be present


= JGroups 4.0.10
* `INJECT_VIEW`: protocol to inject random views (https://issues.jboss.org/browse/JGRP-2243)


= JGroups 4.0.12
* `ASYM_ENCRYPT` simplifications / bugfixes:
** https://issues.jboss.org/browse/JGRP-2270
** https://issues.jboss.org/browse/JGRP-2272
** https://issues.jboss.org/browse/JGRP-2273
** https://issues.jboss.org/browse/JGRP-2274
** https://issues.jboss.org/browse/JGRP-2275
* `MERGE3`: a dead merge leader never leads to a merge (https://issues.jboss.org/browse/JGRP-2276)
* `TUNNEL`: bundling is now supported (https://issues.jboss.org/browse/JGRP-2255)
* `RELAY2`: notifications when someone becomes site master, or ceases to be site master
  (https://issues.jboss.org/browse/JGRP-2267)

= JGroups 4.0.13
* `CENTRAL_LOCK2`: new locking protocol that doesn't use a backup lock manager, but reconciliation when the coordinator
  (lock manager) crashes or leaves
** Less communication during regular operation, but chatty during coordinator crash
** https://issues.jboss.org/browse/JGRP-2249
** Design doc: https://github.com/belaban/JGroups/blob/master/doc/design/CENTRAL_LOCK2.txt

* Change the way a coordinator leaves gracefully
** Same code is now used to handle coord crashes and leaves
** Instead of installing the 'last view', a leaving coord asks the next-in-line to do that
** https://issues.jboss.org/browse/JGRP-2277

* Asynchronous `MERGE3`
** Uses `FIND_MBRS_ASYNC` event to asynchronously do discovery
** Callback is called on _every response_
** Fixes https://issues.jboss.org/browse/JGRP-2281


= JGroups 4.0.16
* Fix for JGRP-2277: graceful leave of coord and next-in-line(s) leaves the cluster with incorrect views
** https://issues.jboss.org/browse/JGRP-2293

* Discovery protocol for members in the same process
** Replacement for `TEST_PING`
** Not the same as `SHARED_LOOPBACK_PING` (which can only be used with `SHARED_LOOPBACK`)
** https://issues.jboss.org/browse/JGRP-2284



= JGroups 5.0

== API changes
* `Message` is now an interface
* Different implementations such as `BytesMessage`, `ObjectMessage`, `NioMessage` etc
** Every message still has a destination and sender address, headers and flags
* Ability to create and register own message types
* This is WIP, will become `master` soon (current master will become `4.x` branch)
* Subsequent releases (`5.1`, `5.2`...) will contain new functionality, but no API changes


== MessageFactory
[source,java]
----
public interface MessageFactory {

    /**
     * Creates a message based on the given ID
     * @param id The ID
     * @param <T> The type of the message
     * @return A message
     */
    <T extends Message> T create(byte id);

    /**
     * Registers a new creator of messages
     * @param type The type associated with the new payload.
     * @param generator The creator of the payload associated with the given type
     */
    void register(byte type, Supplier<? extends Message> generator);
}
----
* The message factory can be set and retrieved from the transport with `get/setMessageFactory()`

== Message implementations

=== BytesMessage
* Equivalent to old `Message`: has a byte array, an offset and a length
* JOL shows exactly the same memory layout as before:

----
[belasmac] /Users/bela$ jol-size.sh org.jgroups.BytesMessage

org.jgroups.BytesMessage object internals:
 OFFSET  SIZE     TYPE DESCRIPTION                    VALUE
      0     4          (object header)                ...
      4     4          (object header)                ...
      8     4          (object header)                ...
     12     2    short BaseMessage.flags              0
     14     1     byte BaseMessage.transient_flags    0
     15     1          (alignment/padding gap)        N/A
     16     4  Address BaseMessage.dest_addr          null
     20     4  Address BaseMessage.src_addr           null
     24     4 Header[] BaseMessage.headers            [null, null, null, null]
     28     4      int BytesMessage.offset            0
     32     4      int BytesMessage.length            0
     36     4   byte[] BytesMessage.buf               null
Instance size: 40 bytes
Space losses: 1 bytes internal + 0 bytes external = 1 bytes total
----
* This is still the most frequently used message used internally by JGroups (followed by `EmptyMessage`)

==== Allocation and performance
* 8 nodes, UPerf with UDP, 80% reads / 20% writes
* Performance is the same as with the old `Message` (~42'000/sec/node)
* Allocation
** TLABs: 7.4GB (master: 7.32), allocation rate TLABs: 126.33MB/sec (master: 124.9)
** Objects: 33.39GB (master: 37.68), allocation rate: 569.98kB/sec (master: 643.08kB/sec)


=== EmptyMessage
* No payload
* Used by JGroups to send messages which contain only flags and headers
* Compact size:
----
[belasmac] /Users/bela$ jol-size.sh org.jgroups.EmptyMessage

org.jgroups.EmptyMessage object internals:
 OFFSET  SIZE     TYPE DESCRIPTION                    VALUE
      0     4          (object header)                ...
      4     4          (object header)                ...
      8     4          (object header)                ...
     12     2    short BaseMessage.flags              0
     14     1     byte BaseMessage.transient_flags    0
     15     1          (alignment/padding gap)        N/A
     16     4  Address BaseMessage.dest_addr          null
     20     4  Address BaseMessage.src_addr           null
     24     4 Header[] BaseMessage.headers            [null, null, null, null]
     28     4          (loss due to the next object alignment)
Instance size: 32 bytes
Space losses: 1 bytes internal + 4 bytes external = 5 bytes total
----

=== NioMessage
* Has a heap-based `ByteBuffer` as payload
* Creation fails if a direct byte buffer is passed to the constructor
* On serialization (in the transport, at send time), the contents of the byte buffer are written to the output stream
directly:
[source,java]
----
protected void writePayload(DataOutput out) throws Exception {
    out.writeInt(buf != null? getLength() : -1);
    if(buf != null) {
        byte[] buffer=buf.array();
        int offset=buf.arrayOffset()+buf.position(), length=buf.remaining();
        out.write(buffer, offset, length);
    }
}
----
* This avoids the conversion of `ByteBuffer` into a byte array, which was passed to the constructor of the old `Message`,
eliminating 1 byte array allocation

=== NioDirectMessage
* Subclass of `NioMessage`
* Has a direct `ByteBuffer` as payload
* Contents are written using a _transfer buffer_:
[source,java]
----
protected void writePayload(DataOutput out) throws Exception {
    out.writeInt(buf != null? getLength() : -1);
    if(buf != null) {
        out.writeBoolean(use_heap_memory);
        // We need to duplicate; or else writing it to the output stream would modify
        // position; this would break potential retransmission

        ByteBuffer copy=buf.duplicate();
        byte[] transfer_buf=new byte[Math.max(copy.remaining()/10, 128)];
        while(copy.remaining() > 0) {
            int bytes=Math.min(transfer_buf.length, copy.remaining());
            copy.get(transfer_buf, 0, bytes);
            out.write(transfer_buf, 0, bytes);
        }
    }
}
----
* We need a transfer buffer as there is no way to transfer the contents of a ByteBuffer directly to
  an output stream; once we have a transport that directly supports ByteBuffers, we can change this

==== Reading an NioDirectMessage from the network
* There's an option (`use_heap_memory`) to use heap memory when reading, otherwise direct (off-heap) memory is used
* A message is read as follows:
[source,java]
----
protected void readPayload(DataInput in) throws Exception {
    int len=in.readInt();
    if(len < 0)
        return;
    use_heap_memory=in.readBoolean();
    byte[] tmp=new byte[len];
    in.readFully(tmp, 0, tmp.length);
    // todo: replace with factory; so users can provide their own allocation mechanism (e.g. pooling)
    buf=createBuffer(tmp, 0, tmp.length);
}
----

[source,java]
----
protected ByteBuffer createBuffer(byte[] array, int offset, int length) {
    return use_heap_memory? super.createBuffer(array, offset, length) :
    (ByteBuffer)ByteBuffer.allocateDirect(length).put(array, offset, length).flip();
}
----
* Note that memory allocation will be pluggable
* If a pool is to be used, we'd probably need to add a `release()` method to `Message`


=== ObjectMessage
* Has an object as payload
* The object has to implement `SizeStreamable`:
[source,java]
----
public interface SizeStreamable extends Streamable {
    /** Returns the size (in bytes) of the marshalled object */
    int serializedSize();
}
----

[source,java]
----
public interface Streamable {
    void writeTo(DataOutput out) throws Exception;
    void readFrom(DataInput in)  throws Exception;
}
----
* Method `serializedSize()` must give the *exact number of bytes* when the object is marshalled
** This will be changed with https://issues.jboss.org/browse/JGRP-2289
* For fragmentation, if this method is incorrect and returns a value that's too low, an `ObjectMessage` may not get
fragmented, leading to possible size problems at the transport (e.g. UDP max datagram packet size of 65k).
* So, once JGRP-2289 is in place, it is better to return a size that errs on the side of too big rather than too small
* The transport calls `Streamable.writeTo(DataOutput)` when the `ObjectMessage` is sent to the network
* The transport calls `Streamable.readFrom(DataInput)` to create the `ObjectMessage` when received from the network


=== ObjectMessageSerializable
* Subclass of `ObjectMessage`, but the payload (`Object`) does not have to implement any interface
* To be used when we have an object whose size we don't know
* The object is serialized into a byte array which is stored along with the object
** This is done just-in-time (e.g. on `getLength()`)
* The byte array is sent to the network
* Use `ObjectMessage` when possible


=== CompositeMessage
* Contains multiple messages
* Messages can have different types
* Similar to `MessageBatch` (for sending)
* Not sure this is useful


=== FRAG4
* Use this protocol with `ObjectMessage`, `CompositeMessage` or `NioDirectMessage`
* Or else we have superfluous marshalling of the object into a byte array (1 unneeded byte array allocation)
* `FRAG4` creates N `FragmentedMessage` instances, each with an offset and length, and a reference to the original
  message
* When serialized, the `FragmentedMessage` uses a `PartialOutputStream` to marshal only the subset of the original
  output stream between offset and length to the output stream



=== More message types
* A message containing multiple payloads?
* `IntMessage`, `LongMessage`


=== Misc
* Remove `dest` field from `BaseMessage`?
* Message without headers?
* What else can be removed?
* Breakout session: reduce memory allocation in Infinispan when sending commands
** `EmptyMessage`, `ObjectMessage`?
