

Workshop outline
================
author: Bela Ban belaban@yahoo.com

Modules for a JGroups workshop. The different modules can be combined into a custom workshop.

Requirements:

* JDK (7 or higher) installed
* IDE installed. I used IntelliJ, but eclipse works, too
** Lab imported into IDE
** JGroups source code imported into IDE


Day 1: Overview, architecture, API, protocols
---------------------------------------------
* Overview of JGroups
** What is it, what is it *not*, use cases
* Architecture
* API
** JChannel, Message, View
** Creating a channel
** Joining a cluster
** Sending and receiving messages
** Handling view changes
** State transfer
** Leaving a cluster
** Closing a channel
* Protocols
** What do the most frequently used protocols do ?
*** UDP/TCP, PING/TCPPING, FD_SOCK/FD/FD_ALL, NAKACK, UNICAST, STABLE,
GMS, UFC/MFC, FRAG, STATE_TRANSFER
** What are the configuration options ?

include::./using.adoc[Overview]

include::./prot_overview.adoc[Protocol overview]


Day 2: Building blocks
----------------------
* RpcDispatcher / MessageDispatcher
** Asynchronous invocation API
** Working with futures
* Distributed caches
* Distributed locks
* Distributed atomic counters
* Distributed task execution

include::./blocks.adoc["Building blocks"]




Day 3-4: Advanced
------------------
* Message flags (OOB, DONT_BUNDLE, NO_FC etc)

* The transport
** Regular, OOB and internal thread pools
** Customization (replacing thread pool, thread and socket factories)

* Message bundling and message batching

* Sending messages synchronously (RSVP)

* Generating custom addresses
* Control over view generation (pinning down a coordinator)

* Asynchronous invocation API

* Fork channels: light weight channels over the same protocol stack

* RELAY2: bridging geographically separated data centers

* Strategies for handling network partitions
** Primary partition, merging data

* Anatomy of a protocol
** Callbacks
** Headers
*** (Efficient) marshalling, magic numbers, protocol IDs and header registration
** Writing your own protocol

* Debugging
** What breakpoints can do (FD, FD_ALL)
** Byteman: installing rules into a running JVM (and removing them again)
*** A look at a unit test _black-box style_

* Simulation
** Network partitions with DISCARD
** Message drops
** Duplicate messages
** Reordering of messages



include::./advanced.adoc["Advanced"]




Day 5: A closer look at protocols
----------------------------------
* Discovery
** PING, TCPPING

* Merging
** MERGE3

* Failure detection
** FD, FD_ALL, FD_SOCK, FD_HOST

* Reliable message transmission and ordering
** NAKACK2, UNICAST3, SEQUENCER, RSVP

* Message stability
** STABLE

* Cluster membership
** GMS

* Flow control
** MFC, UFC

* State transfer
** STATE, STATE_SOCK

* Security
** AUTH, ENCRYPT, (SASL)

* Misc
** FRAG, COMPRESS, STOMP

include::./protocols.adoc["Protocols"]


Day 5: Admin
------------

* Most important config changes from a stock configuration, e.g.
** Timeouts in discovery protocol
** Listing all nodes in TCPPING
** Thread pool configuration (min/max threads, queues)

* Tuning
** UDP/TCP buffer sizes
** Multicasting and flow control (802.3)

* Diagnostics
** Logging
** JMX and jconsole
** probe.sh
*** Getting and setting properties, invoking methods, changing the log level at runtime

* Most common pain points
** Members don't find each other
*** bind_addr
*** IPv4 versus IPv6
** Switch configuration (IGMP snooping)
** Firewalls
* Multicast routing (mcast)
** bind_addr and mcast_addr
** Setting multicast routes for different mcast_addrs

include::./admin.adoc["Admin"]


Todos
-----
* Provide additional labs, e.g. for
** View generation, custom addresses
** AIA
** Transport configuration
* Writing a protocol: demo
* RELAY2 demo