

Workshop outline
================
author: Bela Ban belaban@yahoo.com

Modules for a JGroups workshop. The different modules should be able to be
combined into a custom workshop.



Overview, architecture, API, protocols
--------------------------------------
* Overview of JGroups
** What is it, what is it *not*, use cases
* Architecture
* API
** JChannel, Message, View
** Creating a channel
** Joining a cluster
** Sending and receiving messages
** Handling view changes
** State transfer
** Leaving a cluster
** Closing a channel
* Protocols
** What do the most frequently used protocols do ?
*** UDP/TCP, PING/TCPPING, FD_SOCK/FD/FD_ALL, NAKACK, UNICAST, STABLE,
GMS, UFC/MFC, FRAG, STATE_TRANSFER
** What are the configuration options ?



Building blocks
---------------
* RpcDispatcher / MessageDispatcher
** Asynchronous invocation API
** Working with futures
* Distributed caches
* Distributed locks
* Distributed atomic counters





Advanced
--------
* The transport
** Regular, OOB and internal thread pools
** Customization (replacing thread pool, thread and socket factories)
** Message bundling and message batching

* Message flags (OOB, DONT_BUNDLE, NO_FC etc)
* Sending messages synchronously (RSVP)
* Generating custom addresses
* Control over view generation (pinning down a coordinator)
* Fork channels: light weight channels over the same protocol stack


* Anatomy of a protocol
** Callbacks
** Headers
*** (Efficient) marshalling, magic numbers, protocol IDs and header registration
** Writing your own protocol


* RELAY2: bridging geographically separated data centers

* Tuning
** UDP/TCP buffer sizes
** Multicasting and flow control (802.3)

* Debugging 
** What breakpoints can do
** Byteman: installing rules into a running JVM (and removing them again)
*** A look at a unit test _black-box style_


* Strategies for handling network partitions
** Primary partition, merging data


A closer look at protocols
--------------------------
* Discovery
** PING, TCPPING

* Merging
** MERGE2, MERGE3
** Strategies to handle split brain scenarios

* Failure detection
** FD, FD_ALL, FD_SOCK

* Reliable message transmission and ordering
** NAKACK, UNICAST, SEQUENCER, RSVP

* Message stability
** STABLE

* Cluster membership
** GMS

* Flow control
** MFC, UFC

* State transfer
** STATE_TRANSFER, STATE, STATE_SOCK

* Security
** AUTH and ENCRYPT

* Misc
** FRAG, COMPRESS, STOMP

* Steps to arrive at an optimal configuration
** Decision tree


Admin
-----
* Discuss the provided default stacks (UDP, TCP, perhaps EC2)
* If TCP is used: which protocols can be removed, same with UDP
* Most important config changes, e.g.
** Timeouts in discovery protocol
** Listing all nodes in TCPPING
** Thread pool configuration (min/max threads, queues)
* Diagnostics
** Logging
** JMX and jconsole
** probe.sh
*** Getting and setting properties, invoking methods, changing the log level

* Most common pain points
** Members don't find each other (bind_addr, IPv4)
** Switch configuration (IGMP snooping)
** Firewalls


JGroups and JDG
---------------
* Thread pool configuration, back pressure into JGroups
** Missing heartbeats caused by exhausted thread pools and false suspicions 
* High concurrent access to the same key set --> possible use of total order

