

Workshop outline
================
author: Bela Ban belaban@yahoo.com

Modules and labs for a JGroups workshop. The different modules can be combined into a custom workshop.

Requirements:

* JDK 8
* IDE installed. I used IntelliJ, but eclipse works, too
** JGroups master (= 4.x) source code imported into IDE

Disclaimer
----------
Red Hat supports the JGroups versions packaged in Red Hat JBoss Enterprise Application Platform and
Red Hat JBoss Data Grid for clustering use cases in these products.

For supported JGroups configurations, please refer to the documentation for these products or ask GSS.

Red Hat does not support use of JGroups directly from application code or as a standalone module.
The objective of this workshop/training is to provide deeper knowledge of JGroups internals, it does not imply
Red Hat support for this material.


Day 1: Overview, architecture, API, protocols
---------------------------------------------
* Overview of JGroups
* Architecture
* API
** JChannel, Message, View
** Creating a channel
** Joining a cluster
** Sending and receiving messages
** Handling view changes
** State transfer
** Leaving a cluster
** Closing a channel
* Protocols
** What do the most frequently used protocols do ?
*** UDP/TCP/TCP_NIO2, PING/TCPPING, FD_SOCK/FD_ALL, NAKACK2, UNICAST3, STABLE,
GMS, UFC/MFC, FRAG3, STATE_TRANSFER
** What are the configuration options ?

include::./using.adoc[Overview]

include::./prot_overview.adoc[Protocol overview]


Day 2: Building blocks
----------------------
* Remote procedure calls across a cluster
** Asynchronous invocation API
** Non-blocking RPCs
* Distributed locks
* Distributed atomic counters

include::./blocks.adoc["Building blocks"]



Day 3: A closer look at protocols
----------------------------------
* Transports
** UDP, TCP, TCP_NIO2

* Discovery
** PING, TCPPING
** Cloud based discovery: Kubernetes, AWS, Google Compute Platform Azure

* Merging
** MERGE3

* Failure detection
** FD_ALL, FD_SOCK, FD_HOST

* Reliable message transmission and ordering
** NAKACK2, UNICAST3, SEQUENCER

* Message stability
** STABLE

* Cluster membership
** GMS

* Flow control
** MFC, UFC
** Non-blocking flow control (UFC_NB, MFC_NB)

* State transfer
** STATE, STATE_SOCK

* Security
** AUTH, SYM_ENCRYPT, ASYM_ENCRYPT, SSL_KEY_EXCHANGE

* Misc
** FRAG3, COMPRESS, STOMP

include::./protocols.adoc["Protocols"]





Day 3-4: Advanced
------------------
* Message flags (OOB, DONT_BUNDLE, NO_FC etc)

* The transport
** Thread pools: configuration and sizing
** Customizations (replacing thread pool, thread and socket factories)

* Message bundling and message batching

* Generating custom addresses
* Control over view generation (pinning down a coordinator)

* Asynchronous invocation API

* Fork channels: light weight channels over the same protocol stack

* Network partitions (split brain)
** What causes partitions?
** Strategies to handle them (CAP)
** Primary partition, merging data
** Raft, eventual consistency
* Examples: distributed counters in JGroups and jgroups-raft

* Writing a simple protocol
** Callbacks
** Headers
*** Marshalling, magic numbers, protocol IDs and header registration
** Writing your own protocol

* Debugging
** What breakpoints can do (FD_ALL)
** Byteman: installing rules into a running JVM (and removing them again)
*** A look at a unit test _black-box style_

* Simulation
** Network partitions with DISCARD
** Message drops
** Duplicate messages
** Reordering of messages



include::./advanced.adoc["Advanced"]







Day 5: Admin
------------

* Tuning
** Multicast routing
** Buffers
** Flow control
** Transport thread pools
** Jumbo frames
** Misc (interrupt coalescing, NIC buffers, link bundling)
** UDP vs. TCP
** Message batching
** Retransmission intervals and max retransmit sizes
** Stability


* Diagnostics
** Logging
** JMX and jconsole
** probe.sh
*** Getting and setting properties, invoking methods, changing the log level at runtime, adding protocols dynamically

* The 12 most common pain points
** Members don't find each other
** IPv4 vs IPv6
** Switch configuration (IGMP snooping)
** Firewalls
** etc
* Multicast routing (mcast)
** bind_addr and mcast_addr
** Setting multicast routes for different mcast_addrs

include::./admin.adoc["Admin"]
