

Workshop outline
================

Days 1 and 2 are introductory and are targeted at people who _use_ and
_configure_ JGroups, e.g. a mixture of app programmers and system admins. Pure
system admins should not attend, as we're going to look at code.

The rest of the workshop is hard-core; for people who have used JGroups
before and who are interested in the innards of JGroups, e.g. how a protocol
is written, how STABLE works and how to write services on top of JGroups, or
how to integrate JGroups into their products.


Day 1: overview, architecture, API, protocols
---------------------------------------------
* Overview of JGroups
** What is it, what is it *not*, use cases
* Architecture
* API
** JChannel, Message, View
** Creating a channel
** Joining a cluster
** Sending and receiving messages
** Handling view changes
** State transfer
** Leaving a cluster
** Closing a channel
* Protocols
** What do the most frequently used protocols do ?
*** UDP/TCP, PING/TCPPING, FD_SOCK/FD/FD_ALL, NAKACK, UNICAST, STABLE,
GMS, UFC/MFC, FRAG, STATE_TRANSFER
** What are the configuration options ?



Day 2: building blocks
----------------------
* Building blocks
** RpcDispatcher / MessageDispatcher
*** Asynchronous invocation API
*** Working with futures
* Cluster-wide locking
* Distributed task execution
* Clustered atomic counters

* Diagnostics
** Logging
** JMX and jconsole
** probe.sh
*** Getting and setting properties, invoking methods, changing the log level



Day 3: advanced I
-----------------
* The transport
** Regular, OOB and internal thread pools
** Customization (replacing thread pool, thread and socket factories)
** Message bundling and message batching

* Message flags (OOB, DONT_BUNDLE, NO_FC etc)

* Control over view generation (pinning down a coordinator)

* Fork channels: light weight channels over the same protocol stack


* Anatomy of a protocol
** Callbacks
** Headers
*** (Efficient) marshalling, magic numbers, protocol IDs and header registration
** Writing your own protocol


* RELAY2: bridging geopgraphically separated data centers


* Debugging 
** What breakpoints can do
** Byteman: installing rules into a running JVM (and removing them again)
*** A look at a unit test _black-box style_


* Strategies for handling network partitions
** Primary partition, merging data


Day 4: a closer look at protocols
---------------------------------
* Discovery
** PING, TCPPING

* Merging
** MERGE2, MERGE3

* Failure detection
** FD, FD_ALL, FD_SOCK

* Reliable message transmission and ordering
** NAKACK, UNICAST, SEQUENCER, RSVP

* Message stability
** STABLE

* Cluster membership
** GMS

* Flow control
** MFC, UFC

* State transfer
** STATE_TRANSFER, STATE, STATE_SOCK

* Misc
** FRAG, COMPRESS, STOMP

