

Welcome to the JGroups workshop
===============================
:author: Bela Ban belaban@yahoo.com
:backend: deckjs
:deckjs_transition: fade
:navigation:
:deckjs_theme: web-2.0
:deckjs_transition: fade
:goto:
:menu:
:toc:
:status:


About me
--------
* Bela Ban, Kreuzlingen (Switzerland)
* PhD in Zurich, post-doc at Cornell (1998-1999) where I started JGroups
* 2000-2003: Fujitsu Networking Communications San Jose, CA
* 2003: joined JBoss (as employee 007)
* JBoss was acquired by RedHat in 2006
* Started JBossCache (predecessor of Infinispan) in 2003, worked on it until version 1.4
* Started jgroups-raft end of 2014
* I enjoy biking, mountain biking, tennis, running


Disclaimer
----------
Red Hat supports the JGroups versions packaged in Red Hat JBoss Enterprise Application Platform and
Red Hat JBoss Data Grid for clustering use cases in these products.

For supported JGroups configurations, please refer to the documentation for these products or ask GSS.

Red Hat does not support use of JGroups directly from application code or as a standalone module.
The objective of this workshop/training is to provide deeper knowledge of JGroups internals, it does not imply
Red Hat support for this material.


Introduction
------------
* Who are you?
* What are you working on?
* What's your interest in JGroups / have you used it before?
* What do you expect from this course?


What are we going to do this week ?
-----------------------------------
* Start at 9am every day, end 5pm (last day: end at noon)
* Mon: API and overview of protocols (introductory)
* Mon/Tue: building blocks
* Tue: protocols and advanced (hard)
* Wed/Thu: Advanced (harder)
* Thu: Admin (easy & fun)
* This is a rough schedule
** We can dive into any topic in more detail if folks ask for it
** I try to make this as interactive as possible
** Let's spend a good deal of time on labs and other ad-hoc exercises


Misc
----
* Wifi code
* Restaurant reservation for the week
* Course times, lunch times
* Social activities (if any)


Let's get started !
-------------------
* Unzip workshop.zip onto your laptop
* The slides are under `slides`
* The labs are under `src`
* The source code for JGroups is under `lib/jgroups-<version>-sources.jar`
* Source `workshop` into your favorite IDE
* The JGroups source code can be fetched from GitHub:
** `git clone https://github.com/belaban/JGroups.git`
* This workshop is also on GitHub:
** `git clone https://github.com/belaban/workshop.git`
* Better yet: fork both JGroups and workshop and submit pull requests if you find errors :-)



